//
// Generated file, do not edit! Created by nedtool 5.5 from DestMessage.msg.
//

#ifndef __NFV_FATTREE_DESTMESSAGE_M_H
#define __NFV_FATTREE_DESTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace nfv_fattree {

/**
 * Class generated from <tt>DestMessage.msg:18</tt> by nedtool.
 * <pre>
 * message DestMessage
 * {
 *     int srcServer;
 * 
 *     int path[];
 *     bool visitsSDN[];
 * 
 *     int vnfChain[];
 *     int vnfPos = 0;
 * 
 *     int hopCount = 0;
 * 
 *     simtime_t produced;
 *     simtime_t queued;
 * }
 * </pre>
 */
class DestMessage : public ::omnetpp::cMessage
{
  protected:
    int srcServer;
    int *path; // array ptr
    unsigned int path_arraysize;
    bool *visitsSDN; // array ptr
    unsigned int visitsSDN_arraysize;
    int *vnfChain; // array ptr
    unsigned int vnfChain_arraysize;
    int vnfPos;
    int hopCount;
    ::omnetpp::simtime_t produced;
    ::omnetpp::simtime_t queued;

  private:
    void copy(const DestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DestMessage&);

  public:
    DestMessage(const char *name=nullptr, short kind=0);
    DestMessage(const DestMessage& other);
    virtual ~DestMessage();
    DestMessage& operator=(const DestMessage& other);
    virtual DestMessage *dup() const override {return new DestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrcServer() const;
    virtual void setSrcServer(int srcServer);
    virtual void setPathArraySize(unsigned int size);
    virtual unsigned int getPathArraySize() const;
    virtual int getPath(unsigned int k) const;
    virtual void setPath(unsigned int k, int path);
    virtual void setVisitsSDNArraySize(unsigned int size);
    virtual unsigned int getVisitsSDNArraySize() const;
    virtual bool getVisitsSDN(unsigned int k) const;
    virtual void setVisitsSDN(unsigned int k, bool visitsSDN);
    virtual void setVnfChainArraySize(unsigned int size);
    virtual unsigned int getVnfChainArraySize() const;
    virtual int getVnfChain(unsigned int k) const;
    virtual void setVnfChain(unsigned int k, int vnfChain);
    virtual int getVnfPos() const;
    virtual void setVnfPos(int vnfPos);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual ::omnetpp::simtime_t getProduced() const;
    virtual void setProduced(::omnetpp::simtime_t produced);
    virtual ::omnetpp::simtime_t getQueued() const;
    virtual void setQueued(::omnetpp::simtime_t queued);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DestMessage& obj) {obj.parsimUnpack(b);}

} // namespace nfv_fattree

#endif // ifndef __NFV_FATTREE_DESTMESSAGE_M_H

